- name: Set OS-dependent variables
  include_vars:
    name: os_vars
    dir: vars

- name: Install Duo
  include: package.yml

- name: Place PAM config file
  template: >
    src=pam_duo.conf.j2
    dest={{ duounix_conf_dir }}/pam_duo.conf
  when: duounix_build_pam
