#
# RedHat-like systems
#
- name: Test for the GPG key (RedHat-like)
  shell: rpm -qi gpg-pubkey-15d32efc-\*
  register: rpm_gpg_installed
  when: ansible_os_family == 'RedHat'
  changed_when: False
  failed_when: False

- name: Install the GPG key (RedHat-like)
  become_user: root
  shell: rpm --import "{{ duounix_gpgkey_url }}"
  when: ansible_os_family == 'RedHat' and "rpm_gpg_installed.rc != 0"

- name: Install the repo (RedHat-like)
  yum_repository:
    name: Duo Security Repository
    description: Official Duo Security repository
    baseurl: http://pkg.duosecurity.com/{{ ansible_distribution }}/$releasever/$basearch
    enabled: yes
    gpgcheck: yes
    state: present
  when: ansible_os_family == 'RedHat'

#
# Common
#
- name: Install duo_unix
  package: name={{ duounix_package }} state=present
